### ISSUE TITLE
static_vector should not default construct values on initialisation

### ISSUE THREAD

**Issue by kevin-j-channon** [kevinchannon/wite#3]
At the moment, static vector will default construct objects to the value of the whole capacity of the vector on initialisation. This is clearly suboptimal. For one thing, it requires the values to be default-constructable, which they might not be.

A reasonable solution would be to hold optional values instead. However, this will require implementation of a custom iterative type for static_vector. Not a problem, but it will be a fair amount of typing.

**Comment by kevinchannon** [comment]
This is now fixed in v0.14.0
